name: cmac_env
channels:
- conda-forge
- defaults
dependencies:
- cycler=0.10.0=py36_0
- dbus=1.10.10=3
- distributed=1.25.3
- expat=2.2.1=0
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- glib=2.51.4=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=2
- hdf4=4.2.12=0
- icu=58.1=1
- jpeg=9b=0
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=0
- libxcb=1.12=1
- libxml2=2.9.4=4
- matplotlib=2.0.2=np112py36_0
- pcre=8.39=0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- qt=5.6.2=3
- sip=4.18=py36_1
- six=1.10.0=py36_1
- tornado=4.5.1=py36_0
- trmm_rsl=1.49=2
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- basemap=1.0.7=np112py36_0
- curl=7.49.0=1
- cython=0.25.2=py36_0
- geos=3.5.0=0
- h5py=2.7.0=np112py36_0
- hdf5=1.8.17=2
- libgfortran=3.0.0=1
- libnetcdf=4.4.1=1
- mkl=2017.0.3=0
- netcdf4=1.2.4=np112py36_0
- nose=1.3.7=py36_1
- numpy=1.12.1=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.1=2
- readline=6.2=2
- scipy=0.19.1=np112py36_0
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - git+https://github.com/ARM-DOE/pyart.git
  - git+https://github.com/EVS-ATMOS/cmac2.0.git
  - git+https://github.com/CSU-Radarmet/CSU_RadarTools.git
  - decorator==4.1.1
  - networkx==1.11
  - scikit-fuzzy==0.3
