name: cmac_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - arm_pyart
  - cartopy
  - coincbc
  - cython
  - distributed
  - scikit-fuzzy
  - dask
  - wradlib
  - numpy
  - matplotlib
  - pip
  - pip:
    - git+https://github.com/CSU-Radarmet/CSU_RadarTools.git
    - git+https://github.com/EVS-ATMOS/cmac2.0.git
