name: cmac_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - arm_pyart
  - basemap
  - json
  - gcc
  - cartopy
  - coincbc
  - cython=0.27.3
  - scikit-fuzzy
  - pip:
    - git+https://github.com/ARM-DOE/pyart.git
    - git+https://github.com/CSU-Radarmet/CSU_RadarTools.git
    - git+https://github.com/EVS-ATMOS/cmac2.0.git
