name: cmac_env
channels:
  - conda-forge
  - defaults
  - menpo
dependencies:
  - python=3.6
  - arm_pyart
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - nose
  - basemap
  - trmm_rsl
  - wradlib
  - cartopy
  - xarray
  - coincbc
  - cartopy
  - pip:
    - scikit-fuzzy
    - git+https://github.com/zssherman/xsapr_clutter_project.git
    - git+https://github.com/CSU-Radarmet/CSU_RadarTools.git
    - git+https://github.com/EVS-ATMOS/cmac2.0.git
