#!/usr/bin/env python
""" Generates clutter radar with the option to use dask. """

import argparse
import glob
import os
from time import time

from matplotlib import use
use('agg')

from cmac import tall_clutter


def main():
    """ The main function use calculates clutter for CMAC 2.0. """
    parser = argparse.ArgumentParser(
        description='Create a radar object with applied CMAC2.0.')
    parser.add_argument(
        'radar_path', type=str, help=('Radar path to use for calculations.',
                                      'The program will search recursively',
                                      'for files in the directory. If',
                                      'a file is specified, every file',
                                      'in the list will be processed.'))
    parser.add_argument(
        'out_file_name', type=str, help=('Output Cf/Radial file'))
    parser.add_argument(
        'facility', type=str, help=('Facility ID such as I4, to show which',
                                    'X-SAPR data is being used.')) 
    args = parser.parse_args()
    if os.path.isdir(args.radar_path):
        radar_files = glob.glob(args.radar_path + '/**/*' + args.facility
                                + '*', recursive=True)
    elif os.path.isfile(args.radar_path):
        with open(args.radar_path) as f:
            radar_files = f.readlines()
        radar_files = [x.strip() for x in radar_files]
    else:
        raise IOError('The specified radar path does not exist!')
    bt = time()
    tall_clutter(radar_files, write_radar=True,
                 out_file=args.out_file_name, use_dask=True)
    print('Time to make clutter file: ' + str(time() - bt))

if __name__ == '__main__':
    main()
