#!/bin/bash
#SBATCH -N 1
#SBATCH --account=ATM124
#SBATCH --time=24:00:00 
#SBATCH --mail-user=rjackson@anl.gov

cd /gpfs/wolf/atm124/proj-shared/cmac2.0/scripts
module load python
source activate /ccsopen/home/rjackson/.conda/envs/cmac_env2
python cmac_sail.py {$1}
