name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - arm_pyart
  - numpy
  - cython
  - cartopy
  - coincbc
  - scikit-fuzzy
  - pytest
  - dask
  - distributed
  - pip:
    - git+https://github.com/CSU-Radarmet/CSU_RadarTools.git
