name: cmac_test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - arm_pyart
  - cartopy
  - cmweather
  - coincbc
  - cython
  - dask
  - distributed
  - matplotlib
  - numpy
  - pytest
  - pytest-mpl
  - scikit-fuzzy
  - wradlib
  - xarray
  - pip
  - act-atmos
